export const featuredBrands = [
  {
    id: 1,
    categories : 'clothes',
    brand: "adidas",
    productName: "Clothing Collection",
    price: 78,
    image: "./img/1.jpg",
    rating: 5,
  },
  {
    id: 2,
    categories : 'clothes',
    brand: "Nike",
    productName: "Clothing Collection",
    price: 120,
    image: "./img/2.jpg",
    rating: 4,
  },
  {
    id: 3,
    categories : 'clothes',
    brand: "Puma",
    productName: "Clothing Collection",
    price: 90,
    image: "./img/3.jpg",
    rating: 5,
  },
  {
    id: 4,
    categories : 'clothes',
    brand: "Reebok",
    productName: "Clothing Collection",
    price: 65,
    image: "./img/4.jpg",
    rating: 4,
  },
  {
  id: 5,
  categories : 'clothes',
  brand:  'beauty',
  productName: "Clothing Collection",
  price: 78,
  image: "./img/5.jpg",
  rating: 5,

  },
  {
    id: 6,
    categories :  'clothes',
    brand: "adidas",
    productName: "Clothing Collection",
    price: 78,
    image: "./img/6.jpg",
    rating: 5,
  },
  {
    id: 7,
    categories :  'clothes',
    brand: "Nike",
    productName: "Clothing Collection",
    price: 120,
    image: "./img/7.jpg",
    rating: 4,
  },
  {
    id: 8,
    categories : 'clothes',
    brand: "Puma",
    productName: "Clothing Collection",
    price: 90,
    image: "./img/8.jpg",
    rating: 5,
  },
  {
    id: 9,
    categories :  'clothes',
    brand: "Reebok",
    productName: "Clothing Collection",
    price: 65,
    image: "./img/9.jpg",
    rating: 4,
  },
  {
    id: 10,
    categories :  'clothes',
    brand: "adidas",
    productName: "Clothing Collection",
    price: 78,
    image: "./img/10.jpg",
    rating: 5,
  },
  {
    id: 11,
    categories :  'clothes',
    brand: "Nike",
    productName: "Clothing Collection",
    price: 120,
    image: "./img/11.jpg",
    rating: 4,
  },
  {
    id: 12,
    categories : 'clothes',
    brand: "Puma",
    productName: "Clothing Collection",
    price: 90,
    image: "./img/12.jpg",
    rating: 5,
  },
  {
    id: 13,
    categories : 'beauty',
    brand: "adidas",
    productName: "care-items",
    price: 78,
    image: "./img/13.jpg",
    rating: 5,
  },
  {
    id: 14,
    categories : 'beauty',
    brand: "Nike",
    productName: "care-items",
    price: 120,
    image: "./img/14.jpg",
    rating: 4,
  },
  {
    id: 15,
    categories : 'beauty',
    brand: "Puma",
    productName: "care-items",
    price: 90,
    image: "./img/15.jpg",
    rating: 5,
  },
  {
    id: 16,
    categories : 'beauty',
    brand: "Reebok",
    productName: "care-items",
    price: 65,
    image: "./img/16.jpg",
    rating: 4,
  },
  {
  id: 17,
  categories : 'beauty',
  brand:  'beauty',
  productName: "care-items",
  price: 78,
  image: "./img/17.jpg",
  rating: 5,

  },
  {
    id: 18,
    categories :  'beauty',
    brand: "adidas",
    productName: "care-items",
    price: 78,
    image: "./img/18.jpg",
    rating: 5,
  },
  {
    id: 19,
    categories :  'beauty',
    brand: "Nike",
    productName: "care-items",
    price: 120,
    image: "./img/19.jpg",
    rating: 4,
  },
  {
    id: 20,
    categories : 'beauty',
    brand: "Puma",
    productName: "care-items",
    price: 90,
    image: "./img/20.jpg",
    rating: 5,
  },
  {
    id: 21,
    categories :  'beauty',
    brand: "Reebok",
    productName: "care-items",
    price: 65,
    image: "./img/21.jpg",
    rating: 4,
  },
  {
    id: 22,
    categories :  'beauty',
    brand: "adidas",
    productName: "care-items",
    price: 78,
    image: "./img/22.jpg",
    rating: 5,
  },
  {
    id: 23,
    categories :  'beauty',
    brand: "Nike",
    productName: "care-items",
    price: 120,
    image: "./img/23.jpg",
    rating: 4,
  },
  {
    id: 24,
    categories : 'beauty',
    brand: "Puma",
    productName: "care-items",
    price: 90,
    image: "./img/24.jpg",
    rating: 5,
  },
  {
    id: 26,
    categories : 'gadgets',
    brand: "Nike",
    productName: "Device Collection",
    price: 120,
    image: "./img/26.jpg",
    rating: 4,
  },
  {
    id: 27,
    categories : 'gadgets',
    brand: "Puma",
    productName: "Device Collection",
    price: 90,
    image: "./img/27.jpg",
    rating: 5,
  },
  {
    id: 28,
    categories : 'gadgets',
    brand: "Reebok",
    productName: "Device Collection",
    price: 65,
    image: "./img/28.jpg",
    rating: 4,
  },
  {
  id: 29,
  categories : 'gadgets',
  brand:  'beauty',
  productName: "Device Collection",
  price: 78,
  image: "./img/29.jpg",
  rating: 5,

  },
  {
    id: 30,
    categories :  'gadgets',
    brand: "adidas",
    productName: "Device Collection",
    price: 78,
    image: "./img/30.jpg",
    rating: 5,
  },
  {
    id: 31,
    categories :  'gadgets',
    brand: "Nike",
    productName: "Device Collection",
    price: 120,
    image: "./img/31.jpg",
    rating: 4,
  },
  {
    id: 32,
    categories : 'gadgets',
    brand: "Puma",
    productName: "Device Collection",
    price: 90,
    image: "./img/32.jpg",
    rating: 5,
  },
  {
    id: 33,
    categories :  'gadgets',
    brand: "Reebok",
    productName: "Device Collection",
    price: 65,
    image: "./img/33.jpg",
    rating: 4,
  },
  {
    id: 34,
    categories :  'gadgets',
    brand: "adidas",
    productName: "Device Collection",
    price: 78,
    image: "./img/34.jpg",
    rating: 5,
  },
  {
    id: 35,
    categories :  'gadgets',
    brand: "Nike",
    productName: "Device Collection",
    price: 120,
    image: "./img/35.jpg",
    rating: 4,
  },
  {
    id: 36,
    categories : 'gadgets',
    brand: "Puma",
    productName: "Device Collection",
    price: 90,
    image: "./img/36.jpg",
    rating: 5,
  },
  {
    id: 37,
    categories : 'gadgets',
    brand: "Puma",
    productName: "Device Collection",
    price: 90,
    image: "./img/37.jpg",
    rating: 5,
  },
];